spring:
  application:
    name: challenge
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL:localhost}:5432/sangiorgio
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:root}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog-main.json
  cloud:
    aws:
      credentials:
        access-key: accesskey
        secret-key: secretkey
      region:
        static: us-east-1
        instance-profile: true
        profile:
          name: localstack
      endpoint: http://localhost:4566

queueName:
  partial: partial-payments
  full: full-payments
  over: over-payments

server:
  port: 8080